### ISSUE TITLE
contract.methods.function().send() fails with any kind of argument 

### ISSUE THREAD

**Issue by xenide** [vechain/thorify#122]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

#### Environment information

Thorify version: `thorify version` 1.5.4, 1.5.5<br>
Web3 version: `web3 version`<br>
Commit hash : (if `develop`)

#### Expected behaviour
Function call should succeed 

#### Actual behaviour
Calling a contract's method with send() with any type of argument results in `Error: hex string must have 0x prefix` 

Tried with various versions. 1.5.3 is fine, anything beyond that has this problem. 
#### Steps to reproduce the behaviour
Call any deployed contract's non-view function that takes in an argument 

#### Stacktrace

````
Error: hex string must have 0x prefix
    at Coder.decode (/Users/alexlau/vexchange-all/governance/node_modules/thor-devkit/dist/abi.js:33:23)
    at Object.decodeParameter (/Users/alexlau/vexchange-all/governance/node_modules/thor-devkit/dist/abi.js:71:22)
    at /Users/alexlau/vexchange-all/governance/node_modules/thorify/dist/provider/rpc-methods.js:194:105
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alexlau/vexchange-all/governance/node_modules/thorify/dist/provider/rpc-methods.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

````

**Comment by libotony** [comment]
thank you for reporting @xenide, fixed in v1.5.6
