### ISSUE TITLE
Error executing transaction

### ISSUE THREAD

**Issue by SriramRS** [vechain/thorify#28]
### Tried to execute new transaction using the following code
```
const transactionInfo = async () => {
  const transaction = await web3.eth.sendTransaction({
      from: "0x7567d83b7b8d80addcb281a71d54fc7b3364ffed",
      to: "0xd3ae78222beadb038203be21ed5ce7c9b1bff602",
      value: 100,
  })
}
transactionInfo().catch(err => console.error(err))
```

### Getting Following Error

```
/home/ubuntu/vechain-web3/thorify/dist/thor-interceptor.js:115
                    v.blockNumber = v.block.number;
                                            ^
TypeError: Cannot read property 'number' of undefined
    at Object.ResFormatter (/home/ubuntu/vechain-web3/thorify/dist/thor-interceptor.js:115:45)
    at XMLHttpRequest.request.onreadystatechange (/home/ubuntu/vechain-web3/thorify/dist/http-provider.js:55:38)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/ubuntu/vechain-web3/thorify/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/ubuntu/vechain-web3/thorify/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/ubuntu/vechain-web3/thorify/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/ubuntu/vechain-web3/thorify/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! thorify@0.2.0 compile: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thorify@0.2.0 compile script.

```

> The above code worked earlier..facing this issue after latest pull of VechainThor network

**Comment by libotony** [comment]
@SriramRS please update thorify to latest version

**Comment by SriramRS** [comment]
Working fine
Thanks @libotony
