### ISSUE TITLE
Suggestion: Extending web3.eth.accounts shouldn't modify it's prototype

### ISSUE THREAD

**Issue by decent-dev** [vechain/thorify#38]
In cases where we'd need to use both ETH/VET in the same context (token swaps, multi-platform dapps etc.) - extending and modifying the web3.eth.accounts instance prototype seems to affect other non-thorified instances of Web3 as well. 

For example,
```
const Web3 = require('web3')
const { thorify } = require('thorify')

const THOR_URL = 'http://localhost:8669'
const ETHEREUM_URL = 'ws://localhost:8545'

const web3_eth = new Web3()
const web3_vet = new Web3()

web3_eth.setProvider(new Web3.providers.WebsocketProvider(
    ETHEREUM_URL
))
thorify(web3_vet, THOR_URL) // This could also be web3_vet = thorify(web3_vet, THOR_URL)

web3_vet.eth.accounts.wallet.add(PRIVATE_VET_KEY)
web3_eth.eth.accounts.wallet.add(PRIVATE_ETH_KEY)

const sendTxns = async () => {
    let options = {
        from: getDefaultAddress(web3_eth),
        to: getDefaultAddress(web3_vet),
        value: 100,
        gas: 100000
    }
    return web3_eth.eth.sendTransaction(options)
}

const init = async () => {
    try {
        let tx = await sendTxns()
        console.log('Tx', tx)
    } catch (e) {
        console.log(e.stack)
    }
}
init()
```
results in the Thorified sendTransaction() implementation being called as shown below.

```
Error: Returned error: wrong number of fields in data
    at Object.ErrorResponse (/Users/dev/Projects/web3-tx-test/node_modules/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/Users/dev/Projects/web3-tx-test/node_modules/web3-core-requestmanager/src/index.js:140:36)
    at /Users/dev/Projects/web3-tx-test/node_modules/web3-providers-ws/src/index.js:111:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/Users/dev/Projects/web3-tx-test/node_modules/web3-providers-ws/src/index.js:88:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/dev/Projects/web3-tx-test/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/dev/Projects/web3-tx-test/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/dev/Projects/web3-tx-test/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:180:13)
    at WebSocketConnection.processFrame (/Users/dev/Projects/web3-tx-test/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /Users/dev/Projects/web3-tx-test/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at process._tickCallback (internal/process/next_tick.js:112:11)

```

If in https://github.com/vechain/thorify/blob/master/src/extend/accounts.ts, the web3 functions were reassigned to the web3 instance instead of mutating it's prototype, both web3 instances seem to work together seamlessly.

**Comment by libotony** [comment]
see #40
