### ISSUE TITLE
sendTransaction return TypeError

### ISSUE THREAD

**Issue by aaaqi** [vechain/thorify#5]
``` javascript
const chainTag = await web3.eth.getChainTag();
const blockRef = await web3.eth.getBlockRef();
await web3.eth.sendTransaction({ 
    Nonce: Date.now(),
    Clauses: [
      {
        to: '0x65a50cd5db8cecb01af42b5121db5cbcf5bcee30',
        value: 100000000,
      }
    ],
    ChainTag: chainTag,
    BlockRef: blockRef,
    Gas: 3000000,
    Expiration: 720
  });

(node:4838) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at getWallet (/Users/louding/workspace/vechain.com/thor-demo/node_modules/web3-core-method/src/index.js:456:39)
    at sendRequest (/Users/louding/workspace/vechain.com/thor-demo/node_modules/web3-core-method/src/index.js:533:30)
    at Eth.send [as sendTransaction] (/Users/louding/workspace/vechain.com/thor-demo/node_modules/web3-core-method/src/index.js:583:13)
    at /Users/louding/workspace/vechain.com/thor-demo/src/index.js:40:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by libotony** [comment]
Updated code and README, now `eth.sendTransaction` and `eth.accounts.signTransaction` accepts same parameter and be noted that the parameters only support 1 clause
