### ISSUE TITLE
TypeError: Cannot read property 'sendPayload' of undefined

### ISSUE THREAD

**Issue by theallseingeye** [vechain/thorify#83]
Does thorify not support `sendPayload`?

```
$ node scripts/deploy/deploy.js basic
/home/Working/contracts/node_modules/web3-providers/dist/web3-providers.cjs.js:49
      if (provider.sendPayload && provider.subscribe) {
                   ^

TypeError: Cannot read property 'sendPayload' of undefined
    at ProviderResolver.resolve (/home/Working/contracts/node_modules/web3-providers/dist/web3-providers.cjs.js:49:20)
    at Web3.AbstractWeb3Module (/home/Working/contracts/node_modules/web3-core/dist/web3-core.cjs.js:24:51)
    at new Web3 (/home/Working/contracts/node_modules/web3/dist/web3.cjs.js:30:68)
    at Object.<anonymous> (/home/Working/contracts/truffle.js:7:29)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/Working/contracts/scripts/deploy/deploy.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by theallseingeye** [comment]
This is my deploy:

```
var fs = require('fs');
const applicationConfig = require('../../config.js')
const connectionConfig = require('../../truffle.js')
const connection = connectionConfig.networks[applicationConfig.network]

const deployMetadataFilename = 'build/contractDeploymentAddresses.json'

let deployAddresses
try {
  deployAddresses = require(`../../${deployMetadataFilename}`)
} catch(error) {
  deployAddresses = {}
}

let deployType = process.argv[2] // Provide Basic or Extended jurisdiction type
if (typeof(deployType) === 'undefined') {
  deployType = 'extended'
} else {
  deployType = deployType.toLowerCase()
}

let showAccounts = process.argv[3] // Provide if you'd like to dump accounts

const deployTypeOptions = new Set(['basic', 'extended'])
if (!deployTypeOptions.has(deployType)) {
  console.error('must supply "Basic" or "Extended" as the target!')
  process.exit(1)
}

args = []

let contractImportLocation
if (deployType === 'basic') {
  contractImportLocation = '../../build/contracts/BasicJurisdiction.json'
} else if (deployType === 'extended') {
  contractImportLocation = '../../build/contracts/ExtendedJurisdiction.json'
}

const ContractData = require(contractImportLocation)

let web3 = connection.provider

const Contract = new web3.eth.Contract(ContractData.abi)

async function main() {
  console.log(
    `deploying ${
      deployType
    } jurisdiction to ${
      applicationConfig.network
    } network...`
  )
  
  const accounts = await Promise.resolve(web3.eth.getAccounts())
  if (accounts.length === 0) {
    console.error('cannot find any accounts...')
    process.exit(1)
  }
  
  const account = accounts[0]
  deployAddresses.jurisdictionOwner = account
  console.log(`   deployed by: ${account}`)

  const ContractInstance = await Contract.deploy({
    data: ContractData.bytecode,
    arguments: args
  }).send({
    from: account,
    gas: 8000000,
    gasPrice: '10000000000'
  })

  const deployedAddress = ContractInstance.options.address
  deployAddresses.jurisdiction = deployedAddress
  console.log(`  jurisdiction: ${deployedAddress}`)

  fs.writeFile(
    deployMetadataFilename,
    JSON.stringify(deployAddresses),
    {flag: 'w'},
    err => {
      if (err) {
        console.error(err)
        process.exit(1)
      }
      console.log(`metadata written to ${deployMetadataFilename}`)
      if (showAccounts === 'verbose') {
        console.log()
        console.log(JSON.stringify(deployAddresses, null, 2))
      }
      process.exit(0)
    }
  )
}

main()
```

**Comment by libotony** [comment]
From the info you provided, I believe you are using web3 at a version greater than `1.0.0-beta.37` which is not supported now, check [doc](https://github.com/vechain/thorify/#compatibility) for this info
