### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by BaoPham92** [vechain/thorify#95]
#### Environment information

Thorify version: "^1.4.0"<br>
Web3 version: "^1.2.1"<br>

#### Expected behaviour
- Expected successful ```node index.js``` script run.

#### Actual behaviour

```
▶ node index.js
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
Require stack:
- /Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/fs-extra/lib/fs/index.js
- /Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/fs-extra/lib/index.js
- /Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/swarm-js/lib/api-node.js
- /Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/web3-bzz/src/index.js
- /Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/web3/src/index.js
- /Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/fs-extra/lib/fs/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/fs-extra/lib/fs/index.js',
    '/Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/fs-extra/lib/index.js',
    '/Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/swarm-js/lib/api-node.js',
    '/Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/web3-bzz/src/index.js',
    '/Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/node_modules/web3/src/index.js',
    '/Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/index.js'
  ]
}
```

##### Add Packages

- ```Yarn add thorify```
- ```Yarn add web3```

##### Add usage snippet
```
// ES6 style
import { thorify } from "thorify";
const Web3 = require("web3");		// Recommend using require() instead of import here

const web3 = thorify(new Web3(), "http://localhost:8669");

web3.eth.getBlock("latest").then(res => console.log(res));
// Best block info will be displayed
```
##### Received a error:

``` 
▶ node index.js
/Users/kuso/Desktop/Coding/Projects/Personal/sandbox/VeChain/vechain/server/index.js:2
import { thorify } from "thorify";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

##### Added ES5 snippet instead for Thorify && ``` yarn add graceful-fs ``` to resolve:

```
// ES5 style
const thorify = require("thorify").thorify;
```

-  ```node index.js```

I'm aware this might be minor as I can just ``` yarn add graceful-fs ``` but thought I should report it anyways.

**Comment by libotony** [comment]
Hi, @BaoPham92 thorify does need `graceful-fs` as a dependency, `web3` does. I suggest re-install `web3`(Not familiar with yarn, in npm it's `npm i web3 -S`). Otherwise, it may be an issue with `web3`
